name: Daily Product Update

on: push

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run updateDB
        run: node src/db/server.js
        env:
          KASSAL_BEARER_TOKEN: ${{ secrets.KASSAL_BEARER_TOKEN }} # Set your secret in GitHub
          MONGO_URL: ${{ secrets.MONGO_URI }} # Set your secret in GitHub

