name: Update Database Workflow

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # You can adjust the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run server.js
      run: node server.js

